/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */

fn main() {
    let number_of_triangle_numbers: i32 = 1_000_000;
    let mut triangle_numbers: Vec<i32> = Vec::new();
    let mut count: i32 = 1;

    while count <= number_of_triangle_numbers {
        let mut triangle_number: i32 = 0;
        for i in 1..count + 1 {
            triangle_number += i;
        }
        triangle_numbers.push(triangle_number);
        count += 1;
    }

    let mut counter: i32 = 0;
    for number in triangle_numbers {
        let mut factor_count: i32 = 1;

        for i in 1..number + 1 {
            if number % i == 0 {
                factor_count += 1;
            }
        }

        if counter % 100 == 0 {
            println!("{}: Factor count for {}: {}", counter, number, factor_count);
        }
        if factor_count > 300 {
            println!("{}: {} has more than 300 divisors!", counter, number);
            break;
        }
        counter += 1;
    }
}
